version: '3.7'

services:
  festudy-db:
    platform: linux/x86_64
    image: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festudy
      MYSQL_USER: festudy
      MYSQL_PASSWORD: dev
    volumes:
      - ./db_data:/var/lib/mysql
